".local/bin":
  type: archive
  url: "https://github.com/junegunn/fzf/releases/download/v0.61.0/fzf-0.61.0-{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
".local/bin/mlr":
  type: archive-file
  url: https://github.com/johnkerl/miller/releases/download/v6.12.0/miller-6.12.0-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz
  path: "miller-6.12.0-{{ .chezmoi.os }}-{{ .chezmoi.arch }}/mlr"

".local":
  type: archive
  stripComponents: 1
  {{ if eq .chezmoi.os "darwin" }}
  url: "https://github.com/neovim/neovim/releases/download/stable/nvim-macos-arm64.tar.gz"
  {{ else }}
  url: "https://github.com/neovim/neovim/releases/download/stable/nvim-{{ .chezmoi.os }}-x86_64.tar.gz"
  {{ end }}

".local/bin/kind":
  type: file
  url: "https://kind.sigs.k8s.io/dl/v0.24.0/kind-{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
  executable: true

".local/bin/helm":
  type: archive-file
  url: "https://get.helm.sh/helm-v3.16.1-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
  executable: true
  path: "{{ .chezmoi.os }}-{{ .chezmoi.arch }}/helm"

".local/bin/difft":
  type: archive-file
  {{ if eq .chezmoi.os "darwin" }}
  url: "https://github.com/Wilfred/difftastic/releases/download/0.60.0/difft-aarch64-apple-darwin.tar.gz"
  {{ else }}
  url: "https://github.com/Wilfred/difftastic/releases/download/0.60.0/difft-x86_64-unknown-linux-gnu.tar.gz"
  {{ end }}
  executable: true
  path: "difft"

".local/bin/kubectl":
  type: file
  executable: true
  url: "https://dl.k8s.io/release/v1.31.1/bin/{{ .chezmoi.os }}/{{ .chezmoi.arch }}/kubectl"

".local/bin/k9s":
  type: archive-file
  executable: true
  url: "https://github.com/derailed/k9s/releases/download/v0.32.5/k9s_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
  path: k9s

".local/bin/bat":
  type: archive-file
  executable: true
  stripComponents: 1
  {{ if eq .chezmoi.os "darwin" }}
  url: "https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-v0.24.0-x86_64-apple-darwin.tar.gz"
  {{ else }}
  url: "https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-v0.24.0-x86_64-unknown-linux-gnu.tar.gz"
  {{ end }}
  path: bat

".local/bin/gh":
  type: archive-file
  executable: true
  stripComponents: 1
  {{ if eq .chezmoi.os "darwin" }}
  url: https://github.com/cli/cli/releases/download/v2.60.1/gh_2.60.1_macOS_arm64.zip
  {{ else }}
  url: https://github.com/cli/cli/releases/download/v2.60.1/gh_2.60.1_linux_{{ .chezmoi.arch }}.tar.gz
  {{ end }}
  path: bin/gh

".local/bin/marksman":
  type: file
  executable: true
  {{ if eq .chezmoi.os "darwin" }}
  url: https://github.com/artempyanykh/marksman/releases/download/2024-12-04/marksman-macos
  {{ else }}
  url: https://github.com/artempyanykh/marksman/releases/download/2024-12-04/marksman-linux-x64
  {{ end }}

".local/bin/lf":
  type: archive-file
  url: "https://github.com/gokcehan/lf/releases/download/r33/lf-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
  executable: true
  path: "lf"
